services:
  mongo:
    image: mongo
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - tk-db-data:/data/db
      - tk-db-config:/data/configdb
  toolkeeper:
    image: ghcr.io/daveluhman/toolkeeper
    env_file: compose.env
    restart: unless-stopped
    depends_on:
    - mongo
    ports:
    - 80:3000


volumes:
  tk-db-config:
  tk-db-data: