services:
  mongo:
    image: mongo:4
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - tk-db-data:/data/db
      - tk-db-config:/data/configdb
  toolkeeper:
    image: ghcr.io/daveluhman/toolkeeper:v1.1.6
    env_file: .env
    restart: unless-stopped
    depends_on:
    - mongo
    ports:
    - ${PORT}:3000


volumes:
  tk-db-config:
  tk-db-data: